/** @type {import('stylelint').Config} */
//  Файл конфигурации Stylelint от Igro-Zona
export default {
	// 'stylelint-scss' - плагин с правилами для линтинга SCSS, 'stylelint-order' - плагин для сортировки свойств
	plugins: ["stylelint-scss", "stylelint-order"],
	// 'postcss-scss' плагин позволяет парсить синтаксис SCSS
	customSyntax: "postcss-scss",
	// Правила для работы Stylelint
	rules: {
		// Правила для выявления ошибок в CSS
		"annotation-no-unknown": [true, { ignoreAnnotations: ["default", "global", "optional"] }],
		"at-rule-descriptor-no-unknown": null,
		"at-rule-descriptor-value-no-unknown": null,
		"at-rule-no-deprecated": [true, { severity: "warning" }],
		"at-rule-no-unknown": [
			true,
			{
				ignoreAtRules: [
					"at-root",
					"content",
					"debug",
					"each",
					"else",
					"error",
					"extend",
					"for",
					"forward",
					"function",
					"if",
					"import",
					"include",
					"mixin",
					"return",
					"use",
					"warn",
					"while",
				],
			},
		],
		"at-rule-prelude-no-invalid": null,
		"block-no-empty": [true, { ignore: ["comments"] }, { severity: "warning" }],
		"color-no-invalid-hex": true,
		"comment-no-empty": null,
		"custom-property-no-missing-var-function": true,
		"declaration-block-no-duplicate-custom-properties": true,
		"declaration-block-no-duplicate-properties": [true, { severity: "warning" }],
		"declaration-block-no-shorthand-property-overrides": true,
		"declaration-property-value-keyword-no-deprecated": [true, { severity: "warning" }],
		"declaration-property-value-no-unknown": null,
		"font-family-no-duplicate-names": true,
		"font-family-no-missing-generic-family-keyword": true,
		"function-calc-no-unspaced-operator": [true, { severity: "warning" }],
		"function-linear-gradient-no-nonstandard-direction": true,
		"function-no-unknown": null,
		"keyframe-block-no-duplicate-selectors": true,
		"keyframe-declaration-no-important": true,
		"media-feature-name-no-unknown": true,
		"media-feature-name-value-no-unknown": null,
		"media-query-no-invalid": null,
		"media-type-no-deprecated": true,
		"named-grid-areas-no-invalid": true,
		"nesting-selector-no-missing-scoping-root": null,
		"no-descending-specificity": true,
		"no-duplicate-at-import-rules": true,
		"no-duplicate-selectors": [true, { severity: "warning" }],
		"no-empty-source": true,
		"no-invalid-double-slash-comments": true,
		"no-invalid-position-at-import-rule": [
			true,
			{
				ignoreAtRules: ["use", "forward", "mixin"],
			},
		],
		"no-invalid-position-declaration": true,
		"no-irregular-whitespace": true,
		"no-unknown-animations": true,
		"no-unknown-custom-media": true,
		"no-unknown-custom-properties": null,
		"property-no-deprecated": [true, { severity: "warning" }],
		"property-no-unknown": null,
		"selector-anb-no-unmatchable": true,
		"selector-pseudo-class-no-unknown": null,
		"selector-pseudo-element-no-unknown": true,
		"selector-type-no-unknown": true,
		"string-no-newline": [true, { ignore: ["at-rule-preludes", "declaration-values"] }],
		"syntax-string-no-invalid": true,
		"unit-no-unknown": true,
		// Правила для установки конвенций написания CSS
		"alpha-value-notation": ["number", { severity: "warning" }],
		"at-rule-allowed-list": null,
		"at-rule-disallowed-list": ["import"],
		"at-rule-empty-line-before": [
			"always",
			{
				except: ["blockless-after-same-name-blockless", "blockless-after-blockless", "first-nested"],
				ignore: ["after-comment"],
				ignoreAtRules: ["else"],
				severity: "warning",
			},
		],
		"at-rule-no-vendor-prefix": [true, { severity: "warning" }],
		"at-rule-property-required-list": null,
		"block-no-redundant-nested-style-rules": true,
		"color-function-alias-notation": ["without-alpha", { severity: "warning" }],
		"color-function-notation": ["modern", { severity: "warning" }],
		"color-hex-alpha": "never",
		"color-hex-length": ["long", { severity: "warning" }],
		"color-named": ["always-where-possible", { ignore: ["inside-function"] }],
		"color-no-hex": true,
		"comment-empty-line-before": [
			"always",
			{
				except: ["first-nested"],
				ignore: ["stylelint-commands"],
				severity: "warning",
			},
		],
		"comment-pattern": null,
		"comment-whitespace-inside": ["always", { severity: "warning" }],
		"comment-word-disallowed-list": null,
		"custom-media-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"custom-property-empty-line-before": [
			"always",
			{
				except: ["after-custom-property", "first-nested"],
				ignore: ["after-comment", "inside-single-line-block"],
				severity: "warning",
			},
		],
		"custom-property-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"container-name-pattern": ["^(--)?([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"declaration-block-no-redundant-longhand-properties": [true, { severity: "warning" }],
		"declaration-block-single-line-max-declarations": 1,
		"declaration-empty-line-before": [
			"always",
			{
				except: ["after-declaration", "first-nested"],
				ignore: ["after-comment", "inside-single-line-block"],
				severity: "warning",
			},
		],
		"declaration-no-important": null,
		"declaration-property-max-values": null,
		"declaration-property-unit-allowed-list": null,
		"declaration-property-unit-disallowed-list": null,
		"declaration-property-value-allowed-list": null,
		"declaration-property-value-disallowed-list": null,
		"font-family-name-quotes": ["always-where-recommended", { severity: "warning" }],
		"font-weight-notation": ["numeric", { severity: "warning" }],
		"function-allowed-list": null,
		"function-disallowed-list": null,
		"function-name-case": ["lower", { severity: "warning" }],
		"function-url-no-scheme-relative": true,
		"function-url-quotes": ["always", { severity: "warning" }],
		"function-url-scheme-allowed-list": null,
		"function-url-scheme-disallowed-list": null,
		"hue-degree-notation": ["angle", { severity: "warning" }],
		"import-notation": ["string", { severity: "warning" }],
		"keyframes-name-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"keyframe-selector-notation": ["percentage-unless-within-keyword-only-block", { severity: "warning" }],
		"layer-name-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"length-zero-no-unit": [
			true,
			{
				ignore: ["custom-properties"],
				ignorePreludeOfAtRules: ["function", "mixin"],
				severity: "warning",
			},
		],
		"lightness-notation": ["percentage", { severity: "warning" }],
		"max-nesting-depth": null,
		"media-feature-name-allowed-list": null,
		"media-feature-name-disallowed-list": null,
		"media-feature-name-no-vendor-prefix": [true, { severity: "warning" }],
		"media-feature-range-notation": ["context", { severity: "warning" }],
		"media-feature-name-unit-allowed-list": null,
		"media-feature-name-value-allowed-list": null,
		"number-max-precision": 4,
		"property-allowed-list": null,
		"property-disallowed-list": null,
		"property-no-vendor-prefix": [true, { severity: "warning" }],
		"rule-empty-line-before": [
			"always-multi-line",
			{
				except: ["first-nested"],
				ignore: ["after-comment"],
				severity: "warning",
			},
		],
		"rule-selector-property-disallowed-list": null,
		"selector-attribute-quotes": ["always", { severity: "warning" }],
		"selector-max-attribute": null,
		"selector-max-class": null,
		"selector-max-combinators": null,
		"selector-max-compound-selectors": null,
		"selector-max-id": 0,
		"selector-max-pseudo-class": null,
		"selector-max-specificity": null,
		"selector-max-type": null,
		"selector-max-universal": null,
		"selector-not-notation": ["complex", { severity: "warning" }],
		"selector-attribute-name-disallowed-list": null,
		"selector-attribute-operator-allowed-list": null,
		"selector-attribute-operator-disallowed-list": null,
		"selector-class-pattern": null,
		"selector-combinator-allowed-list": null,
		"selector-combinator-disallowed-list": null,
		"selector-disallowed-list": null,
		"selector-id-pattern": ["^([a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"selector-nested-pattern": null,
		"selector-no-vendor-prefix": [true, { severity: "warning" }],
		"selector-pseudo-class-allowed-list": null,
		"selector-pseudo-class-disallowed-list": null,
		"selector-pseudo-element-allowed-list": null,
		"selector-pseudo-element-colon-notation": ["double", { severity: "warning" }],
		"selector-pseudo-element-disallowed-list": null,
		"selector-type-case": ["lower", { severity: "warning" }],
		"shorthand-property-no-redundant-values": [true, { severity: "warning" }],
		"time-min-milliseconds": null,
		"unit-allowed-list": null,
		"unit-disallowed-list": ["dppx", "q", "mm", "dpcm", "cm", "dpi", "in", "pt", "pc", "ex"],
		"value-keyword-case": ["lower", { severity: "warning" }],
		"value-no-vendor-prefix": [true, { severity: "warning" }],
		// Правила для выявления ошибок и установки конвенций написания SCSS
		"scss/at-each-key-value-single-line": true,
		"scss/at-else-closing-brace-newline-after": ["always-last-in-chain", { severity: "warning" }],
		"scss/at-else-closing-brace-space-after": ["always-intermediate", { severity: "warning" }],
		"scss/at-else-empty-line-before": ["never", { severity: "warning" }],
		"scss/at-else-if-parentheses-space-before": ["always", { severity: "warning" }],
		"scss/at-extend-no-missing-placeholder": true,
		"scss/at-function-named-arguments": "never",
		"scss/at-function-parentheses-space-before": ["never", { severity: "warning" }],
		"scss/at-function-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"scss/at-if-closing-brace-newline-after": ["always-last-in-chain", { severity: "warning" }],
		"scss/at-if-closing-brace-space-after": ["always-intermediate", { severity: "warning" }],
		"scss/at-if-no-null": true,
		"scss/at-import-partial-extension-allowed-list": null,
		"scss/at-import-partial-extension-disallowed-list": null,
		"scss/at-mixin-argumentless-call-parentheses": ["never", { severity: "warning" }],
		"scss/at-mixin-named-arguments": "never",
		"scss/at-mixin-no-risky-nesting-selector": true,
		"scss/at-mixin-parentheses-space-before": ["never", { severity: "warning" }],
		"scss/at-mixin-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"scss/at-rule-conditional-no-parentheses": [true, { severity: "warning" }],
		"scss/at-rule-no-unknown": true,
		"scss/at-use-no-redundant-alias": true,
		"scss/at-use-no-unnamespaced": null,
		"scss/block-no-redundant-nesting": null,
		"scss/comment-no-empty": true,
		"scss/comment-no-loud": true,
		"scss/declaration-nested-properties-no-divided-groups": true,
		"scss/declaration-nested-properties": "never",
		"scss/declaration-property-value-no-unknown": true,
		"scss/dimension-no-non-numeric-values": true,
		"scss/dollar-variable-colon-newline-after": ["always-multi-line", { severity: "warning" }],
		"scss/dollar-variable-colon-space-after": ["at-least-one-space", { severity: "warning" }],
		"scss/dollar-variable-colon-space-before": ["never", { severity: "warning" }],
		"scss/dollar-variable-default": null,
		"scss/dollar-variable-empty-line-after": ["always", { except: "before-dollar-variable", severity: "warning" }],
		"scss/dollar-variable-empty-line-before": [
			"always",
			{
				except: ["after-dollar-variable", "first-nested"],
				severity: "warning",
			},
		],
		"scss/dollar-variable-first-in-block": null,
		"scss/dollar-variable-no-missing-interpolation": true,
		"scss/dollar-variable-no-namespaced-assignment": null,
		"scss/dollar-variable-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"scss/double-slash-comment-empty-line-before": [
			"always",
			{
				except: ["first-nested"],
				ignore: ["between-comments", "stylelint-commands"],
				severity: "warning",
			},
		],
		"scss/double-slash-comment-inline": null,
		"scss/double-slash-comment-whitespace-inside": ["always", { severity: "warning" }],
		"scss/function-calculation-no-interpolation": true,
		"scss/function-color-channel": true,
		"scss/function-color-relative": true,
		"scss/function-disallowed-list": null,
		"scss/function-no-unknown": null,
		"scss/function-quote-no-quoted-strings-inside": [true, { severity: "warning" }],
		"scss/function-unquote-no-unquoted-strings-inside": [true, { severity: "warning" }],
		"scss/load-no-partial-leading-underscore": true,
		"scss/load-partial-extension": ["never", { severity: "warning" }],
		"scss/map-keys-quotes": "always",
		"scss/media-feature-value-dollar-variable": null,
		"scss/no-dollar-variables": null,
		"scss/no-duplicate-dollar-variables": true,
		"scss/no-duplicate-load-rules": true,
		"scss/no-duplicate-mixins": true,
		"scss/no-global-function-names": true,
		"scss/no-unused-private-members": true,
		"scss/operator-no-newline-after": true,
		"scss/operator-no-newline-before": true,
		"scss/operator-no-unspaced": true,
		"scss/partial-no-import": true,
		"scss/percent-placeholder-pattern": ["^(-?[a-z][a-z0-9]*)(-[a-z0-9]+)*$"],
		"scss/property-no-unknown": true,
		"scss/selector-nest-combinators": null,
		"scss/selector-no-redundant-nesting-selector": null,
		"scss/selector-no-union-class-name": null,

		"order/properties-order": [
			"content",
			"box-sizing",
			"position",
			"inset",
			"top",
			"right",
			"bottom",
			"left",
			"z-index",
			"object-fit",
			"overflow",
			"overflow-x",
			"overflow-y",
			"display",
			"justify-content",
			"align-items",
			"gap",
			"row-gap",
			"column-gap",
			"max-width",
			"width",
			"min-width",
			"max-height",
			"height",
			"min-height",
			"margin",
			"margin-block",
			"margin-inline",
			"margin-top",
			"margin-right",
			"margin-bottom",
			"margin-left",
			"border",
			"border-block",
			"border-inline",
			"border-top",
			"border-right",
			"border-bottom",
			"border-left",
			"border-color",
			"border-radius",
			"padding",
			"padding-block",
			"padding-inline",
			"padding-top",
			"padding-right",
			"padding-bottom",
			"padding-left",
			"background",
			"background-attachment",
			"background-color",
			"background-image",
			"background-position",
			"background-repeat",
			"background-size",
			"color",
			"font",
			"font-family",
			"font-size",
			"font-smoothing",
			"osx-font-smoothing",
			"font-style",
			"font-weight",
			"hyphens",
			"src",
			"line-height",
			"letter-spacing",
			"word-spacing",
			"text-align",
			"text-decoration",
			"text-indent",
			"text-overflow",
			"text-rendering",
			"text-size-adjust",
			"text-shadow",
			"text-transform",
			"word-break",
			"word-wrap",
			"white-space",
			"vertical-align",
			"outline",
			"pointer-events",
			"cursor",
			"opacity",
			"filter",
			"visibility",
			"transform",
			"transition",
			"transition-delay",
			"transition-duration",
			"transition-property",
			"transition-timing-function",
			"animation",
			"animation-delay",
			"animation-duration",
			"animation-iteration-count",
			"animation-name",
			"animation-play-state",
			"animation-timing-function",
			"animation-fill-mode",
		],
	},
	// Перезапись парсера для обработки html-подобных форматов
	overrides: [
		{
			files: ["**/*.astro", "**/*.html", "**/*.jsx", "**/*.tsx"],
			customSyntax: "postcss-html",
		},
	],
};
